site_name: XSLT
site_url: https://xsltdev.ru/
site_description: Справочник XSLT-разработчика с примерами кода
site_author: xsltdev.ru
copyright: (C) 2012-2021, Справочник XSLT и XPath с примерами кода

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/xsltdev.ru'

theme:
    name: material
    custom_dir: overrides
    palette:
        primary: black
        accent: teal
    language: ru
    features:
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
    favicon: xslt.svg
    logo: xslt.svg

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - attr_list
    - md_in_html

plugins:
    - search:
          separator: '[\s\-\:]+'
          prebuild_index: true
          lang:
              - ru
              - en
    - awesome-pages
    - section-index
    
extra:
    generator: false
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/xsltdev
          name: Группа в Telegram

extra_css:
    - '/assets/stylesheets/styles.css'
